name: CI
on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-$${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests: # Runs tests using resuable test workflow on all PR's to main
    uses: ./.github/workflows/test.yaml
    secrets: inherit
